# input directories
haps_dir = "notebooks/data/demo/party2/haps/" # containing all_chrs.[pgen|pvar|psam]
snp_list = "notebooks/data/demo/snpsForKING.txt"
gmap_dir = "notebooks/data/demo/gmap/" # containing chr[1-22].gmap.gz
maf_dir = "notebooks/data/demo/maf/" # containing chr[1-22].maf.gz

# where to cache intermediate files
pos_dir = "notebooks/data/demo/pos/" # containing chr[1-22]_pos.txt
geno_dir = "notebooks/data/demo/party2/geno/" # genotypes (reconstructed from haplotypes in haps_dir)
sketched_snps_dir = "notebooks/data/demo/sketched/" ## share this with the other party
shared_param_dir = "notebooks/data/demo/params/" ## share this with the other party
hash_table_dir = "notebooks/data/demo/party2/table/" ## local hash table directory

#output directory is the same as the config directory