separator = ' '

# should update the data directory correspondingly
simple_data_path = "notebooks/data/2party_100/geno/party1/all_chrs_maf0.01.bin" 
row_index_file= "notebooks/data/2party_100/table/mode4cM8len80k8/tables/party1/ID_table.npz"
column_index_file= "notebooks/data/2party_100/sketched/SNPs_70.npz"