# This is the directory the binary genotype 
# file of all individuals. Each genotype is 
# encoded as a byte in individual-major order.
# So there are a total of n * M bytes.
simple_data_path = "notebooks/trial/party2/geno/all_chrs.bin"
# this is the output by the Python step1 script
row_index_file= "notebooks/trial/party2/table/ID_table.npz"
# this is the output by the Python step0b script.
column_index_file="notebooks/trial/sketched/SNPs.npz"